export const leagues = [
  {
    id:1,
    title: "La Liga",
    description:
      "The top professional football league in Spain, known for its tactical approach and passionate fanbase.",
    numClubs: 40,
    rating: 8.5,
    logo: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Real_Madrid_logo.svg/normal.svg",
    clubs: [
      {
        name: "Real Madrid",
        trophies: ["Champions League", "Club World Cup", "Copa del Rey"],
        fans: 6000000,
        stadium: "Santiago Bernabéu",
        president: "Ana Betiz-López",
      },
      {
        name: "Barcelona",
        trophies: ["Champions League", "Copa del Rey", "Supercopa de España"],
        fans: 6500000,
        stadium: "Camp Nou",
        president: "Joan Laporta",
      },
      {
        name: "Atlético Madrid",
        trophies: ["Champions League", "Supercopa de España", "Copa del Rey"],
        fans: 6200000,
        stadium: "Wanda Cruz",
        president: "Diego Simeone",
      },
      {
        name: "Manchester United",
        trophies: ["Champions League", "Premier League", "Europa League"],
        fans: 6800000,
        stadium: "Old Trafford",
        president: "Bruno Fernandes",
      },
      {
        name: "Arsenal",
        trophies: ["Premier League", "FA Cup", "League Cup"],
        fans: 6300000,
        stadium: "Emirates Stadium",
        president: "Arsen Wenger",
      },
      {
        name: "Bayern Munich",
        trophies: [
          "Champions League",
          "Dayer's Derby",
          "Supercopa de Alemania",
        ],
        fans: 5800000,
        stadium: "Allianz Arena",
        president: "Joαßan Hofmann",
      },
      {
        name: "Liverpool",
        trophies: ["Champions League", "Premier League", "Europa League"],
        fans: 6600000,
        stadium: "Anfield",
        president: "Jürgen Klopp",
      },
    ],
  },
  {
    id:2,
    title: "Premier League",
    description:
      "The top professional football league in England, known for its competitive fixtures and exciting matches.",
    numClubs: 20,
    rating: 8.2,
    logo: "https://upload.wikimedia.org/wikipedia/commons/6/63/Premier_League_logo.svg/normal.svg",
    clubs: [
      {
        name: "Manchester United",
        trophies: ["Champions League", "Club World Cup", "Premier League"],
        fans: 6800000,
        stadium: "Old Trafford",
        president: "Erik ten Hag",
      },
      {
        name: "Arsenal",
        trophies: ["Champions League", "Premier League", "Europa League"],
        fans: 6300000,
        stadium: "Emirates Stadium",
        president: "Jürgen Klopp",
      },
      {
        name: "Liverpool",
        trophies: ["Champions League", "Premier League", "Europa League"],
        fans: 6600000,
        stadium: "Anfield",
        president: "Jürgen Klopp",
      },
      {
        name: "Tottenham Hotspur",
        trophies: ["Premier League", "FA Cup", "League Cup"],
        fans: 6400000,
        stadium: "Angeyster Stadium",
        president: "Antonio Conte",
      },
      {
        name: "Chelsea",
        trophies: ["Premier League", "Europa League", "Champions League"],
        fans: 6200000,
        stadium: "Willingham Park",
        president: "Thomas Tuchel",
      },
      {
        name: "Manchester City",
        trophies: ["Champions League", "Premier League", "Europa League"],
        fans: 6900000,
        stadium: " Etihad Stadium",
        president: "Pep Guardiola",
      },
      {
        name: "Aston Villa",
        trophies: ["Premier League", "FA Cup", "League Cup"],
        fans: 6000000,
        stadium: "Villa Park",
        president: "Dean Bosworth",
      },
    ],
  },
  {
    id:3,
    title: "Serie A",
    description:
      "The top professional football league in Italy, renowned for its tradition, flair, and passionate fanbase.",
    numClubs: 40,
    rating: 8.1,
    logo: "https://upload.wikimedia.org/wikipedia/commons/3/37/Real_Madrid_logo.svg/normal.svg",
    clubs: [
      {
        name: "Juventus",
        trophies: ["Champions League", "Serie A", "Supercopa de Italia"],
        fans: 5200000,
        stadium: "Juventus Stadium",
        president: "Paulo Pastrana",
      },
      {
        name: "Inter Milan",
        trophies: ["Champions League", "Serie A", "Supercopa de Italia"],
        fans: 5300000,
        stadium: "San Siro",
        president: "Inter Milan",
      },
      {
        name: "AC Milan",
        trophies: ["Champions League", "Serie A", "Supercopa de Italia"],
        fans: 5100000,
        stadium: "San Siro",
        president: "Leonardo Maldini",
      },
    ],
  },
];
